[project]
name = "tts_cli"
version = "0.1.0"
description = "CLI to convert text files to voice audio using Azure Speech Studio"
dependencies = [
  "azure-cognitiveservices-speech",
  "PyPDF2",
  "python-docx"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
